### PR TITLE
cp,pipe: don't omit some of the metadata flags

### LINKED ISSUE #657: cp: acl: seems acl set broken in 2.2.1
Hi, the acl seems was omitted, when I was try `cp` with 2.2.1 version

```python
√ /tmp % s5cmd --stat cp --acl "public-read" "*rpm" s3://k0ste/rpm-legacy/
cp netdata-plugin-perf-1.42.2-1.el8.x86_64.rpm s3://k0ste/rpm-legacy/netdata-plugin-perf-1.42.2-1.el8.x86_64.rpm
cp netdata-plugin-pythond-1.42.2-1.el8.x86_64.rpm s3://k0ste/rpm-legacy/netdata-plugin-pythond-1.42.2-1.el8.x86_64.rpm
cp netdata-plugin-apps-1.42.2-1.el8.x86_64.rpm s3://k0ste/rpm-legacy/netdata-plugin-apps-1.42.2-1.el8.x86_64.rpm
cp netdata-plugin-debugfs-1.42.2-1.el8.x86_64.rpm s3://k0ste/rpm-legacy/netdata-plugin-debugfs-1.42.2-1.el8.x86_64.rpm
cp netdata-plugin-ebpf-1.42.2-1.el8.x86_64.rpm s3://k0ste/rpm-legacy/netdata-plugin-ebpf-1.42.2-1.el8.x86_64.rpm
cp netdata-ebpf-legacy-code-1.42.2-1.el8.x86_64.rpm s3://k0ste/rpm-legacy/netdata-ebpf-legacy-code-1.42.2-1.el8.x86_64.rpm
cp netdata-1.42.2-1.el8.x86_64.rpm s3://k0ste/rpm-legacy/netdata-1.42.2-1.el8.x86_64.rpm

Operation	Total	Error	Success
cp		1	0	1
√ 111 % s3cmd info s3://k0ste/rpm-legacy/netdata-1.42.2-1.el8.x86_64.rpm
s3://k0ste/rpm-legacy/netdata-1.42.2-1.el8.x86_64.rpm (object):
   File size: 13778140
   Last mod:  Wed, 30 Aug 2023 13:40:07 GMT
   MIME type: application/octet-stream
   Storage:   STANDARD
   MD5 sum:   10885f5846e179ae10e3b764662e9f05
   SSE:       none
   Policy:    none
   CORS:      none
   ACL:       <account>: FULL_CONTROL <------ no ACL for anon-read
```

Checked with s3cmd:

```python
√ /tmp % s3cmd --recursive --acl-public put 111/ s3://k0ste/rpm-legacy/
upload: '111/netdata-1.42.2-1.el8.x86_64.rpm' -> 's3://k0ste/rpm-legacy/netdata-1.42.2-1.el8.x86_64.rpm'  [1 of 7]
 13778140 of 13778140   100% in    1s    10.12 MB/s  done
upload: '111/netdata-ebpf-legacy-code-1.42.2-1.el8.x86_64.rpm' -> 's3://k0ste/rpm-legacy/netdata-ebpf-legacy-code-1.42.2-1.el8.x86_64.rpm'  [2 of 7]
 3694284 of 3694284   100% in    0s    15.77 MB/s  done
upload: '111/netdata-plugin-apps-1.42.2-1.el8.x86_64.rpm' -> 's3://k0ste/rpm-legacy/netdata-plugin-apps-1.42.2-1.el8.x86_64.rpm'  [3 of 7]
 385860 of 385860   100% in    0s     4.23 MB/s  done
upload: '111/netdata-plugin-debugfs-1.42.2-1.el8.x86_64.rpm' -> 's3://k0ste/rpm-legacy/netdata-plugin-debugfs-1.42.2-1.el8.x86_64.rpm'  [4 of 7]
 348728 of 348728   100% in    0s     3.05 MB/s  done
upload: '111/netdata-plugin-ebpf-1.42.2-1.el8.x86_64.rpm' -> 's3://k0ste/rpm-legacy/netdata-plugin-ebpf-1.42.2-1.el8.x86_64.rpm'  [5 of 7]
 599716 of 599716   100% in    0s     5.07 MB/s  done
upload: '111/netdata-plugin-perf-1.42.2-1.el8.x86_64.rpm' -> 's3://k0ste/rpm-legacy/netdata-plugin-perf-1.42.2-1.el8.x86_64.rpm'  [6 of 7]
 347276 of 347276   100% in    0s  1944.90 KB/s  done
upload: '111/netdata-plugin-pythond-1.42.2-1.el8.x86_64.rpm' -> 's3://k0ste/rpm-legacy/netdata-plugin-pythond-1.42.2-1.el8.x86_64.rpm'  [7 of 7]
 270216 of 270216   100% in    0s     2.80 MB/s  done
√ /tmp % s3cmd info s3://k0ste/rpm-legacy/netdata-1.42.2-1.el8.x86_64.rpm
s3://k0ste/rpm-legacy/netdata-1.42.2-1.el8.x86_64.rpm (object):
   File size: 13778140
   Last mod:  Wed, 30 Aug 2023 13:46:13 GMT
   MIME type: application/x-rpm
   Storage:   STANDARD
   MD5 sum:   10885f5846e179ae10e3b764662e9f05
   SSE:       none
   Policy:    none
   CORS:      none
   ACL:       *anon*: READ  <----- ACL for anon-read present
   ACL:       <account>: FULL_CONTROL
```

### PR DESCRIPTION
**Pull request by denizsurmeli**
#657 mentioned that `acl` flag was broken in `v2.2.1`. After looking at the issue, it was discovered that not only the `acl` flag was broken, there are couple of more flags that were being omitted during the mentioned commands, which all of them caused by this faulty [PR](https://github.com/peak/s5cmd/pull/621). 

Resolves #657.

### CODE REVIEW

**Review by seruman — COMMENTED** [review]
I've missed these on the review, sorry. While you're at it, what do you think about adding test cases for each metadata flag if possible? I think we could have catch this early with failing tests.

**Comment by denizsurmeli** [comment]
I'm afraid that some of the metadata flags(`acl`, `expires` and `cache-control`)  are not supported by `gofakes3`.  We can try to patch the fork or we can run these tests against a `minio` or `localstack` instance maybe ?

**Comment by denizsurmeli** [comment]
[This PR](https://github.com/igungor/gofakes3/pull/11) adds support for missing metadata flags, except for the `ACL`, since the `ACL` of the object is not a part of the `s3.GetObjectResult` but a  separate call, namely the `s3.GetObjectACL`. This call however is not implemented in `gofakes3`, I'm working on an implementation but it might take a while. I have prepared the tests for all other flags except `ACL`, which I will push to this branch after the `gofakes3` PR is merged.

**Comment by denizsurmeli** [comment]
@seruman, [5394a50](https://github.com/peak/s5cmd/pull/658/commits/5394a5067994849fbca57906b54d3690fa48c7b0) covers all flags except the `ACL`. Would you like to discuss a strategy on how should we test that feature ? Currently, `gofakes3` does not implement `ACL` related features, we either can work on that feature for it or prepare an "integration" test where we run the test against a `minio` or `localstack` instance, really any `s3` compatible storage service where it supports `ACL` features.

File: e2e/cp_test.go [hunk 1]
```diff
@@ -720,6 +721,111 @@ func TestCopySingleFileToS3(t *testing.T) {
...
+	cmd := s5cmd("cp",
+		"--cache-control", cacheControl,
+		"--expires", expires,
+		"--storage-class", storageClass,
+		"--content-type", ContentType,
+		"--content-disposition", ContentDisposition,
+		"--content-encoding", ContentEncoding,
+		"--sse", EncryptionMethod,
+		"--sse-kms-key-id", EncryptionKeyID,
+		srcpath, dstpath)
```
Comment (seruman) [inline e2e/cp_test.go:770]: let's format it to be a single element per line.

File: e2e/cp_test.go [hunk 2]
```diff
@@ -720,6 +721,111 @@ func TestCopySingleFileToS3(t *testing.T) {
...
+	assert.Assert(t, ensureS3Object(s3client, bucket, filename, content,
+		ensureExpires(expectedExpires),
+		ensureCacheControl(cacheControl),
+		ensureStorageClass(storageClass),
+		ensureContentType(ContentType),
+		ensureContentDisposition(ContentDisposition),
+		ensureContentEncoding(ContentEncoding),
+		ensureEncryptionMethod(EncryptionMethod),
+		ensureEncryptionKeyID(EncryptionKeyID),
+	))
```
Comment (seruman) [inline e2e/cp_test.go:787]: let's format it to be a single element per line.

File: e2e/cp_test.go [hunk 3]
```diff
@@ -720,6 +721,111 @@ func TestCopySingleFileToS3(t *testing.T) {
...
+
+}
+
+// NOTE: This test needs an implementation of the
+// `ACL` feature in gofakes3.
+func TestCopySingleFileToS3WithACLFlag(t *testing.T) {
+	t.Skip()
```
Comment (seruman) [inline e2e/cp_test.go:794]: > Would you like to discuss a strategy on how should we test that feature ? Currently, gofakes3 does not implement ACL related features, we either can work on that feature for it or prepare an "integration" test where we run the test against a minio or localstack instance, really any s3 compatible storage service where it supports ACL features.


If it would not require much test setup i'm on the side of adding it. There's already an integration test for `select` which only runs if an endpoint has given.

**It is not a blocker though IMHO** as this PR is a bug fix, if we can assert that it fixed -manually- we may add the automated tests later in some another PR.

Comment (denizsurmeli) [reply e2e/cp_test.go]: [c177bb2](https://github.com/peak/s5cmd/pull/658/commits/c177bb21ee01cf103651fca7d713d0df30e1bdf2), unfortunately `minio` does not support `ACL` features. We should add this test to the backlog.

**Review by ilkinulas — DISMISSED** [review]

**Review by seruman — DISMISSED** [review]

**Review by igungor — APPROVED** [review]

**Review by seruman — APPROVED** [review]
