### PR TITLE
fix: cp command S3toS3 --content-type flag

### LINKED ISSUE #738: cp command S3toS3 --content-type flag not working
In s5cmd, the --content-type flag does not work when performing an S3 to S3 copy operation with the cp command.

### Object Info

```bash 
> aws --endpoint-url=http://localhost:4566 s3api head-object --bucket copy-test --key src/test.txt
```

```json
{
    "AcceptRanges": "bytes",
    "LastModified": "2024-07-10T08:06:17+00:00",
    "ContentLength": 12,
    "ETag": "\"90a6f0c908b76d95b8d9c0e6405b2fd5\"",
    "ContentType": "text/plain",
    "ServerSideEncryption": "AES256",
    "Metadata": {}
}
```

### AWS CLI Test
```bash
> aws --endpoint-url=http://localhost:4566 s3 cp  s3://copy-test/src/test.txt s3://copy-test/dest/test.txt --content-type video/mp4
```
```bash
copy: s3://copy-test/src/test.txt to s3://copy-test/dest/test.txt
```

```bash
> aws --endpoint-url=http://localhost:4566 s3api head-object --bucket copy-test --key dest/test.txt
```

```json
{
    "AcceptRanges": "bytes",
    "LastModified": "2024-07-10T08:09:34+00:00",
    "ContentLength": 12,
    "ETag": "\"90a6f0c908b76d95b8d9c0e6405b2fd5\"",
    "ContentType": "video/mp4",
    "ServerSideEncryption": "AES256",
    "Metadata": {}
}

```

### s5cmd test
```bash
> s5cmd --endpoint-url=http://localhost:4566 cp --content-type video/mp4 s3://copy-test/src/test.txt s3://copy-test/dest/test2.txt

```
```bash
cp s3://copy-test/src/test.txt s3://copy-test/dest/test2.txt
```

```bash
> aws --endpoint-url=http://localhost:4566 s3api head-object --bucket copy-test --key dest/test2.txt
```

```json
{
    "AcceptRanges": "bytes",
    "LastModified": "2024-07-10T08:17:09+00:00",
    "ContentLength": 12,
    "ETag": "\"90a6f0c908b76d95b8d9c0e6405b2fd5\"",
    "ContentType": "text/plain",
    "ServerSideEncryption": "AES256",
    "Metadata": {}
}
```

### PR DESCRIPTION
**Pull request by 4o4x**
In s5cmd, the --content-type flag does not work when performing an S3 to S3 copy operation with the cp command. 

Added tests addressing this issue.

resolves #738

### CODE REVIEW

**Comment by denizsurmeli** [comment]
Hi, thanks for the PR, can you edit the PR description that indicating https://github.com/peak/s5cmd/issues/738 is resolved by adding "Resolves #PR" in a seperate line.  You can take a look at [this](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) for full reference.

**Comment by ilkinulas** [comment]
@4o4x is this PR ready for review? if not ready, convert it to draft please.

**Comment by denizsurmeli** [comment]
@4o4x tests fail. Can you fix them? Then the PR can be reviewed.

File: storage/s3.go [hunk 1]
```diff
@@ -555,6 +555,13 @@ func (s *S3) Copy(ctx context.Context, from, to *url.URL, metadata Metadata) err
 		input.MetadataDirective = aws.String(metadata.Directive)
 	}
 
+	if metadata.ContentType != "" {
+		input.ContentType = aws.String(metadata.ContentType)
+		if metadata.Directive == "" {
+			input.MetadataDirective = aws.String("REPLACE")
+		}
+	}
+
```
Comment (denizsurmeli) [inline storage/s3.go:564]:
```suggestion
	if metadata.ContentType != "" {
		input.ContentType = aws.String(metadata.ContentType)
	}
	
	if metadata.Directive == "" {
	         input.MetadataDirective = aws.String("REPLACE")
	}
```
Two of them are independent. One's value should not effect the other for the request. `MetadataDirective` can be set even when `ContentType` is empty.

File: command/cp.go [hunk 2]
```diff
@@ -530,6 +530,10 @@ func (c Copy) Run(ctx context.Context) error {
 			if c.metadataDirective == "" {
 				// default to COPY
 				c.metadataDirective = "COPY"
+				if c.src.IsRemote() && c.dst.IsRemote() && c.contentType != "" {
+					// default to REPLACE for content type change
+					c.metadataDirective = "REPLACE"
+				}
```
Comment (denizsurmeli) [inline command/cp.go:536]: Does the `aws` cli shows the same behaviour ? I believe it defaults to `COPY` in all cases, the user explicitly needs to pass `REPLACE`: https://arc.net/l/quote/grqlrdlq

File: e2e/cp_test.go [hunk 3]
```diff
@@ -58,57 +58,57 @@ func TestCopySingleS3ObjectToLocal(t *testing.T) {
 			name:        "cp s3://bucket/object .",
 			src:         "file1.txt",
 			dst:         ".",
-			expected:    fs.WithFile("file1.txt", fileContent, fs.WithMode(0644)),
+			expected:    fs.WithFile("file1.txt", fileContent, fs.WithMode(0o644)),
```
Comment (denizsurmeli) [inline e2e/cp_test.go:61]: Regarding these formatting changes, even though it's not important on this PR, it's better to decouple cosmetic changes with the actual changes(bugfix, feature etc.). No need to revert for this one.

File: e2e/cp_test.go [hunk 4]
```diff
@@ -4596,3 +4591,183 @@ func TestCopyS3ObjectsWithIncludeExcludeFilter2(t *testing.T) {
...
+	s3client, s5cmd := setup(t)
+
+	createBucket(t, s3client, srcbucket)
+	createBucket(t, s3client, dstbucket)
+
+	fileAndContent := map[string]string{
+		"file1.txt":                "this is a test file 1",
+		"file2.html":               "<html><body><h1>file2</h1></body></html>",
+		"file3.mp4":                "this is a test file 3",
+		"file4.py":                 "import tensorflow as tf",
```
Comment (denizsurmeli) [inline e2e/cp_test.go:4742]: Four files are not needed to assert that content type is set to the desired value. One file is enough. Adding one for flat, one for nested case is sufficient. It becomes harder to main the tests after some point when other stuff keeps testing the same thing over and over, adding tests that cover the possible cases and leaving at that point is more sustainable :)

File: e2e/cp_test.go [hunk 5]
```diff
@@ -4596,3 +4591,183 @@ func TestCopyS3ObjectsWithIncludeExcludeFilter2(t *testing.T) {
...
+	createBucket(t, s3client, bucket)
+
+	// create files with different content types
+
+	folderLayout := []fs.PathOp{
+		fs.WithFile("file1.html", "<html><body><h1>file1</h1></body></html>"),
+		fs.WithFile("file2.text", "this is a test file 2"),
+		fs.WithFile("file3.mp4", "this is a test file 3"),
+		fs.WithFile("file4.py", "import tensorflow as tf"),
+		fs.WithFile("readme.md", "this is a readme file"),
```
Comment (denizsurmeli) [inline e2e/cp_test.go:4647]: Same comment below 👇

**Review by denizsurmeli — CHANGES_REQUESTED** [review]

File: command/cp.go [hunk 6]
```diff
@@ -530,6 +530,10 @@ func (c Copy) Run(ctx context.Context) error {
 			if c.metadataDirective == "" {
 				// default to COPY
 				c.metadataDirective = "COPY"
+				if c.src.IsRemote() && c.dst.IsRemote() && c.contentType != "" {
+					// default to REPLACE for content type change
+					c.metadataDirective = "REPLACE"
```
Comment (denizsurmeli) [inline command/cp.go:535]: Since `COPY` and `REPLACE` are referenced in multiple places, it would be better to make them consts.

File: command/cp.go (hunk 2 above)
Comment (4o4x) [reply command/cp.go:536]: # AWS CLI Test

## Object Metadata Before Copy
```shell
aws --endpoint-url=http://localhost:4566 s3api head-object --bucket copy-test --key dest/test.txt
```

```json
{
    "AcceptRanges": "bytes",
    "LastModified": "2024-07-22T08:46:26+00:00",
    "ContentLength": 12,
    "ETag": "\"90a6f0c908b76d95b8d9c0e6405b2fd5\"",
    "ContentType": "text/plain",
    "ServerSideEncryption": "AES256",
    "Metadata": {}
}
```

## Copy Without metadirective flag
```
aws --endpoint-url=http://localhost:4566 s3 cp  s3://copy-test/dest/test.txt s3://copy-test/dest/test.txt --content-type video/mp4
```

```
copy: s3://copy-test/dest/test.txt to s3://copy-test/dest/test.txt
```
## Object Metadata After Copy 
```
aws --endpoint-url=http://localhost:4566 s3api head-object --bucket copy-test --key dest/test.txt
```

```json
{
    "AcceptRanges": "bytes",
    "LastModified": "2024-07-22T08:46:40+00:00",
    "ContentLength": 12,
    "ETag": "\"90a6f0c908b76d95b8d9c0e6405b2fd5\"",
    "ContentType": "video/mp4",
    "ServerSideEncryption": "AES256",
    "Metadata": {}
}
```

File: storage/s3.go (hunk 1 above)
Comment (4o4x) [reply storage/s3.go:564]: Actually, there is no need for a second condition because this code block already covers this case.

```go
  if c.metadataDirective == "" {
          // default to COPY
          c.metadataDirective = "COPY"
          if c.src.IsRemote() && c.dst.IsRemote() && c.contentType != "" {
                  // default to REPLACE for content type change
                  c.metadataDirective = "REPLACE"
          }
  }
```

Comment (denizsurmeli) [reply storage/s3.go:564]: It's very confusing to follow. The nested if's can be flattened, it's easier for reading&understanding. Also, the code block checks only if the `contentType` is not empty but the `metadataDirective` affects all metadata related fields, `contentDisposition, metadata` etc. If it's going to be set `REPLACE` when `s3-to-s3` copy will be performed, why `contentType` is only metadata related field to be checked ? It looks like we shouldn't decide based on the `contentType` but only to check if the transfer is `s3-to-s3`. Also, the directive should be set above of all metadata related fields, since it affects those fields, regarding the code block in `storage/s3.go`(L558 and forward). Also if the `command/cp.go` sets the default value, why do we need to set a value to `metadataDirective` in `storage/s3.go` ?

File: command/cp.go (hunk 2 above)
Comment (denizsurmeli) [reply command/cp.go:536]: Thanks for the demonstration, the document agrees with your result: https://arc.net/l/quote/ksyjgxlm

File: e2e/cp_test.go (hunk 3 above)
Comment (4o4x) [reply e2e/cp_test.go]: done.

File: e2e/cp_test.go (hunk 4 above)
Comment (4o4x) [reply e2e/cp_test.go]: done.

File: e2e/cp_test.go (hunk 5 above)
Comment (4o4x) [reply e2e/cp_test.go]: done.

File: command/cp.go (hunk 6 above)
Comment (4o4x) [reply command/cp.go:535]:
```
const (
	metadataDirectiveCopy    = "COPY"
	metadataDirectiveReplace = "REPLACE"
)
```

Is it appropriate ?

File: storage/s3.go (hunk 1 above)
Comment (denizsurmeli) [reply storage/s3.go:564]: Sounds right 👍 The tests should cover the second point: 
>In the suggestion change code you wrote, only the first condition is necessary. This is because the meta-directive will already be determined before reaching this point.

File: command/cp.go (hunk 6 above)
Comment (denizsurmeli) [reply command/cp.go:535]: It looks okay, it's hard to name things :)

File: e2e/cp_test.go [hunk 7]
```diff
@@ -4596,3 +4596,160 @@ func TestCopyS3ObjectsWithIncludeExcludeFilter2(t *testing.T) {
...
+		assert.Assert(t, ensureS3Object(s3client, srcbucket, filename, content))
+	}
+
+	for filename, content := range fileAndContent {
+		assert.Assert(t, ensureS3Object(s3client, dstbucket, filename, content))
+	}
+
+	for filename, content := range fileAndContent {
+		assert.Assert(t, ensureS3Object(s3client, dstbucket, filename, content, ensureContentType("video/avi")))
+	}
```
Comment (denizsurmeli) [inline e2e/cp_test.go:4754]: Why is it required to assert multiple times after no modification ? Is this on purpose ?

File: e2e/cp_test.go [hunk 8]
```diff
@@ -4596,3 +4596,160 @@ func TestCopyS3ObjectsWithIncludeExcludeFilter2(t *testing.T) {
...
+
+	srcpath := workdir.Join(filename)
+	dstpath := fmt.Sprintf("s3://%v/", bucket)
+
+	cmd := s5cmd("cp", "--content-type", "video/mp4", srcpath, dstpath)
+
+	result := icmd.RunCmd(cmd)
+	result.Assert(t, icmd.Success)
+
+	// assert local filesystem
```
Comment (denizsurmeli) [inline e2e/cp_test.go:4625]: no need for the comments above the assertions. It's clear what it asserts.

File: e2e/cp_test.go [hunk 9]
```diff
@@ -4596,3 +4596,160 @@ func TestCopyS3ObjectsWithIncludeExcludeFilter2(t *testing.T) {
...
+	expected := fs.Expected(t, fs.WithFile(filename, content))
+	assert.Assert(t, fs.Equal(workdir.Path(), expected))
+
+	// assert s3
```
Comment (denizsurmeli) [inline e2e/cp_test.go:4629]: no need for the comments above the assertions. It's clear what it asserts.

File: e2e/cp_test.go [hunk 10]
```diff
@@ -4596,3 +4596,160 @@ func TestCopyS3ObjectsWithIncludeExcludeFilter2(t *testing.T) {
...
+		t.Skip("Files in Windows cannot contain glob(*) characters")
+	}
+	t.Parallel()
+
+	s3client, s5cmd := setup(t)
+
+	bucket := s3BucketFromTestName(t)
+	createBucket(t, s3client, bucket)
+
+	// create files with different content types
```
Comment (denizsurmeli) [inline e2e/cp_test.go:4645]: no need for this comment, it's clear in the code.

File: e2e/cp_test.go [hunk 11]
```diff
@@ -4596,3 +4596,160 @@ func TestCopyS3ObjectsWithIncludeExcludeFilter2(t *testing.T) {
...
+
+	src := fmt.Sprintf("%v/*", workdir.Path())
+	dst := fmt.Sprintf("s3://%v/", bucket)
+
+	cmd := s5cmd("cp", "--content-type", "video/avi", src, dst)
+
+	result := icmd.RunCmd(cmd)
+	result.Assert(t, icmd.Success)
+
+	// assert local filesystem
```
Comment (denizsurmeli) [inline e2e/cp_test.go:4666]: the comment above applies all other comments above the assertions too

File: e2e/cp_test.go (hunk 8 above)
Comment (4o4x) [reply e2e/cp_test.go:4625]: I added these comments because there were similar ones in the old tests.

Comment (denizsurmeli) [reply e2e/cp_test.go:4625]: No need to carry those comments to this PR imo.

File: e2e/cp_test.go (hunk 7 above)
Comment (4o4x) [reply e2e/cp_test.go:4754]: yes it was but I am gonna delete first two.

File: e2e/cp_test.go (hunk 11 above)
Comment (4o4x) [reply e2e/cp_test.go]: done.

File: e2e/cp_test.go (hunk 10 above)
Comment (4o4x) [reply e2e/cp_test.go]: done.

File: e2e/cp_test.go (hunk 9 above)
Comment (4o4x) [reply e2e/cp_test.go]: done.

File: e2e/cp_test.go (hunk 8 above)
Comment (4o4x) [reply e2e/cp_test.go]: done.

File: e2e/cp_test.go (hunk 7 above)
Comment (4o4x) [reply e2e/cp_test.go]: done.

File: command/cp.go (hunk 6 above)
Comment (4o4x) [reply command/cp.go]: done.

File: storage/s3.go (hunk 1 above)
Comment (4o4x) [reply storage/s3.go]: done.

File: e2e/cp_test.go [hunk 12]
```diff
@@ -866,6 +866,11 @@ func TestCopyS3ToS3WithArbitraryMetadataWithDefaultDirective(t *testing.T) {
 		"Key2": aws.String("value2"),
 	}
 
+	destmetadata := map[string]*string{
```
Comment (denizsurmeli) [inline e2e/cp_test.go:869]:
```suggestion
	dstmetadata := map[string]*string{
```
To be consistent

Comment (4o4x) [reply e2e/cp_test.go]: done 😄

File: e2e/cp_test.go [hunk 13]
```diff
@@ -4596,3 +4601,141 @@ func TestCopyS3ObjectsWithIncludeExcludeFilter2(t *testing.T) {
...
+
+	assert.Assert(t, ensureS3Object(s3client, bucket, filename, content, ensureContentType("video/mp4")))
+}
+
+// cp --content-type "video/avi" dir s3://bucket/
+func TestCopyMultipleFilesToS3BucketWithContentType(t *testing.T) {
+	if runtime.GOOS == "windows" {
+		t.Skip("Files in Windows cannot contain glob(*) characters")
+	}
+	t.Parallel()
```
Comment (denizsurmeli) [inline e2e/cp_test.go:4641]:
```suggestion
	t.Parallel()
	if runtime.GOOS == "windows" {
		t.Skip("Files in Windows cannot contain glob(*) characters")
	}
```

Comment (4o4x) [reply e2e/cp_test.go]: done.

**Review by denizsurmeli — DISMISSED** [review]

**Review by igungor — APPROVED** [review]

**Review by igungor — CHANGES_REQUESTED** [review]
Could you update Changelog file?

File: CHANGELOG.md [hunk 14]
```diff
@@ -8,6 +8,9 @@
 - Added prefix and wildcard support to `cat` command. ([#716](https://github.com/peak/s5cmd/issues/716))
 - Added `head` command. ([#730](https://github.com/peak/s5cmd/pull/730))
 
+#### Bugfixes
+- Fixed `cp` command to flag to work with --content-type when performing a copy operation S3 to S3. ([#738](https://github.com/peak/s5cmd/issues/738))
```
Comment (igungor) [inline CHANGELOG.md:12]:
```suggestion
- Fixed the `cp` command to work with the `--content-type` flag when performing a copy operation from S3 to S3. ([#738](https://github.com/peak/s5cmd/issues/738))
```

**Review by igungor — APPROVED** [review]

**Review by denizsurmeli — APPROVED** [review]
