### PR TITLE
Follow symbolic links

### LINKED ISSUE #17: Invalid symbolic link to directory with --parents
Tested with `s5cmd 0.6.0`

When using `--parents` parameter with `cp`, the symbolic link to a directory is managed as file

```
$ find tests -ls
  3318055      4 drwxrwxr-x   3 murlock  murlock      4096 Jun 17 11:59 test/
  3282596      0 lrwxrwxrwx   1 murlock  murlock        10 Jun 17 11:59 test/toto -> tata/160MB
  3282588      0 lrwxrwxrwx   1 murlock  murlock         4 Jun 17 11:59 test/tutu -> tata
  3281209      4 -rw-r--r--   1 murlock  murlock       111 Jun 17 11:58 test/magic
  3318056      4 drwxrwxr-x   2 murlock  murlock      4096 Jun 17 11:58 test/tata
  3281650      4 -rw-r--r--   1 murlock  murlock       111 Jun 17 11:58 test/tata/magic
  3282576 163844 -rw-rw-r--   1 murlock  murlock  167772160 Jun 17 11:58 test/tata/160MB
$ s5cmd  -endpoint-url http://127.0.0.1:5000 -us 5  cp --parents test/ s3://s5cmd/test2/
                    # Uploading magic... (111 bytes)
                    # Uploading 160MB... (167772160 bytes)
                    # Uploading magic... (111 bytes)
                    # Uploading toto... (167772160 bytes)
                    # Uploading tutu... (4096 bytes)
                    + "cp --parents test/magic s3://s5cmd/test2/magic"
                    + "cp --parents test/tata/magic s3://s5cmd/test2/tata/magic"
                    - "cp --parents test/tutu s3://s5cmd/test2/tutu": MultipartUpload: upload multipart failed upload id: ODgyNzQyZmUtNzkzYy00ZGNjLThjN2MtOGZkODRmMTdiOTJl caused by: EntityTooLarge: Your proposed upload exceeds the maximum allowed object size. status code: 400, request id: tx9cb2eb104ddb4fa0a26f2-005d079de3, host id: tx9cb2eb104ddb4fa0a26f2-005d079de3
                    + "cp --parents test/toto s3://s5cmd/test2/toto"
                    + "cp --parents test/tata/160MB s3://s5cmd/test2/tata/160MB"
2019/06/17 16:04:23 -ERR "cp test/ s3://s5cmd/test2/": Not all jobs completed successfully: 4/5
2019/06/17 16:04:24 # All workers idle, finishing up...
```

A strace show that symbolic link `tutu` was treated as file:
```
10057 newfstatat(AT_FDCWD, "test/tutu", {st_mode=S_IFDIR|0775, st_size=4096, ...}, 0) = 0                                           
10057 openat(AT_FDCWD, "test/tutu", O_RDONLY|O_CLOEXEC <unfinished ...>                                                             
10059 <... connect resumed> )           = -1 EINPROGRESS (Operation now in progress)                                                
10057 <... openat resumed> )            = 10      
10057 lseek(10, 0, SEEK_CUR)            = 0                                                                                         
10057 lseek(10, 0, SEEK_END)            = 9223372036854775807  
10061 pread64(10, 0xc00031c000, 32768, 1844674407370956) = -1 EISDIR (Is a directory)  
```

and network trace show the result of `lseek` used as-is:
```
    PUT /s5cmd/test2/tutu?partNumber=1&uploadId=NjEwZTE3MTYtMmUxNC00N2E4LWFjODgtOTFlMzYwYTM3NmJk HTTP/1.1\r\n
    Content-Length: 922337203685478\r\n
```

### PR DESCRIPTION
**Pull request by ilkinulas**
- resolves #17 
- added `--no-follow-symlinks` flag to cp command.
- by default s5cmd follows symbolic links

### CODE REVIEW

File: command/cp.go [hunk 1]
```diff
@@ -80,6 +80,10 @@ var copyCommandFlags = []cli.Flag{
 		Name:  "parents",
 		Usage: "create same directory structure of source, starting from the first wildcard",
 	},
+	&cli.BoolFlag{
+		Name:  "no-follow-symlinks",
+		Usage: "do not follow symbolic links (s5cmd follows symbolic links by default)",
```
Comment (igungor) [inline command/cp.go]: cli package prints the default value. we may not need `(s5cmd follows symbolic links by default)`

File: command/expand_test.go [hunk 2]
```diff
@@ -175,6 +179,162 @@ func TestExpandSources(t *testing.T) {
...
+		),
+		fs.WithDir(
+			"b",
+		),
+	}
+
+	workdir := fs.NewDir(t, "expandsourcetest", folderLayout...)
+	defer workdir.Remove()
+
+	os.Symlink(workdir.Join("a/f1.txt"), workdir.Join("b/my_link"))
```
Comment (igungor) [inline command/expand_test.go]: Is `fs.WithSymlink` not do the job?

File: storage/storage.go [hunk 3]
```diff
@@ -21,6 +21,9 @@ var (
 	ErrNoObjectFound = fmt.Errorf("no object found")
 )
 
+// FollowSymlinks is used to check the value of --no-follow-symlinks flag globally
+var FollowSymlinks = true
```
Comment (igungor) [inline storage/storage.go]: instead of a global, we can pass `followSymlink` to storage.List method.

Comment (ilkinulas) [reply storage/storage.go]: I think `symbolic links` is not a part of the storage abstraction. I do not prefer adding `followSymlink` parameter to  the interface. I am thinking of a better way than using a global variable.

Comment (igungor) [reply storage/storage.go]: why not? symlink is actually a part of the storage. some storage systems have support, some don't.

An object's type could be a symlink, or a file, or a directory.
List method could have support for following symlinks, or visiting directories.

Comment (ilkinulas) [reply storage/storage.go]: Because I didn't want to add another empty implementation like `storage.MakeBucket`. 
https://github.com/peak/s5cmd/blob/1c8d8274e1f44f9c17312877e3e70060032dfcc3/storage/fs.go#L190

Comment (igungor) [reply storage/storage.go]: I don't follow. We don't need any method or an empty implementation. S3 will ignore the flag, Filesystem storage will pass it to the godirwalk.Walk. Do I miss something?

Comment (ilkinulas) [reply storage/storage.go]: Tried your suggestion, updated the PR.  It is better than having a global variable. thanks!

Comment (igungor) [reply storage/storage.go]: 🚀

File: storage/fs.go [hunk 4]
```diff
@@ -119,28 +123,33 @@ func walkDir(ctx context.Context, storage Storage, src *url.URL, fn func(o *Obje
 			fileurl.SetRelative(src.Absolute())
 
 			obj, err := storage.Stat(ctx, fileurl)
+
+			//skip if symlink is pointing to a file and --no-follow-symlink
+			if !ShouldProcessUrl(fileurl, followSymlinks) {
```
Comment (igungor) [inline storage/fs.go]: this call is made after storage.Stat. we should move it before the stat call.
