### PR TITLE
storage/url: fixes the bug where some part of destination path is removed by cp

### LINKED ISSUE #360: part of a path removed by cp
I have run into the following strange behavior (on 1.4.0):
```
mkdir -p /mnt/data/folder/wildcard
touch /mnt/data/folder/wildcard/name
s5cmd cp "/mnt/data/folder/*/name" s3://bucket/folder/
cp /mnt/data/folder/wildcard/name s3://bucket/wildcard/name
```
For some reason target does not have `folder`.

### PR DESCRIPTION
**Pull request by kucukaslan**
…oved by `cp`

The cause of problem is a little bit weird.

(url).SetRelative method was given the source (abs.) path as it was provided in command line arguments including the  wildcard characters(* and ?). Hence it determined relative path incorrectly, where "expected" relative path became "../expected" which in turn caused the some part of destination to be lost (since path/filepath.Join converts e.g. /a/b/../c to /a/c)

We also need to identify whether the * and ? characters present in base strings are part of key or they are used for wildcard operation. So we need to know if the "raw" flag is given. To. solve this I changed (URL).SetRelative method to take argument of type URL rather than string.

Fixes peak#360

ps. This PR is aimed for the v2.1.0.

### CODE REVIEW

File: storage/url/url.go [hunk 1]
```diff
@@ -278,8 +278,23 @@ func (u *URL) Clone() *URL {
...
-	dir := filepath.Dir(base)
+// if the base path contains `globCharacters` then, the
+// relative path is determined wrt the parent directory
+// of the so called wildcarded object.
+func (u *URL) SetRelative(base *URL) {
+	baseDir := base.Absolute()
+	if base.IsWildcard() {
+		// note: IsWildcard already computes the loc indirectly
+		// so we could've changed the conditon to be slightly more efficient
+		// but "Clear is better than clever."
```
Comment (aykutfarsak) [inline storage/url/url.go:289]: Maybe we can change this comment with an alternative one that tells us what the below code does and maybe why.

Comment (MuhammedCanKucukaslan) [reply storage/url/url.go]: Thanks for the feedback, I've updated the comment.

File: storage/url/url.go [hunk 2]
```diff
@@ -278,9 +278,37 @@ func (u *URL) Clone() *URL {
 }
 
 // SetRelative explicitly sets the relative path of u against given base value.
-func (u *URL) SetRelative(base string) {
-	dir := filepath.Dir(base)
-	u.relativePath, _ = filepath.Rel(dir, u.Absolute())
+// if the base path contains `globCharacters` then, the
+// relative path is determined wrt the parent directory
+// of the so called wildcarded object.
```
Comment (seruman) [inline storage/url/url.go:283]:
```suggestion
// If the base path contains `globCharacters` then, the relative path is
// determined with respect to the parent directory of the so called wildcarded
// object.
```
**Nitpick:**
Comments are usually 80 chars per line there is more space that we can use. Also, personally not a huge fan of ambiguous abbrevations like *wrt*, is is respect, regard or reference? 🙃

File: e2e/cp_test.go [hunk 3]
```diff
@@ -1004,6 +1004,165 @@ func TestCopyMultipleFilesToS3Bucket(t *testing.T) {
 	}
 }
 
+// adresses the #360
+// cp parent/*/name.txt s3://bucket/newfolder
+func TestCopyMultipleFilesWithWildcardedDirectoryToS3Bucket(t *testing.T) {
+
```
Comment (seruman) [inline e2e/cp_test.go:1010]: Empy lines could be removed.

File: e2e/cp_test.go [hunk 4]
```diff
@@ -1004,6 +1004,165 @@ func TestCopyMultipleFilesToS3Bucket(t *testing.T) {
...
+	//
+	// // assert s3
+	for filename, content := range expectedS3Content {
+		assert.Assert(t, ensureS3Object(s3client, bucket, filename, content))
+	}
+}
+
+// cp parent/c*/name.txt s3://bucket/newfolder
+func TestCopyMultipleFilesEndWildcardedToS3Bucket(t *testing.T) {
+
```
Comment (seruman) [inline e2e/cp_test.go:1065]: Please remove empty line.

File: e2e/cp_test.go [hunk 5]
```diff
@@ -1004,6 +1004,165 @@ func TestCopyMultipleFilesToS3Bucket(t *testing.T) {
...
+	//
+	// // assert s3
+	for filename, content := range expectedS3Content {
+		assert.Assert(t, ensureS3Object(s3client, bucket, filename, content))
+	}
+}
+
+// cp parent/c*1/name.txt s3://bucket/newfolder
+func TestCopyMultipleFilesMiddleWildcardedDirectoryToS3Bucket(t *testing.T) {
+
```
Comment (seruman) [inline e2e/cp_test.go:1120]: Please remove empty line.

File: e2e/sync_test.go [hunk 6]
```diff
@@ -246,6 +246,62 @@ func TestSyncLocalFolderToS3EmptyBucket(t *testing.T) {
 	}
 }
 
+// adresses the #360
+// cp parent/*/name.txt s3://bucket/newfolder
+func TestSyncMultipleFilesWithWildcardedDirectoryToS3Bucket(t *testing.T) {
+
```
Comment (seruman) [inline e2e/sync_test.go:252]: Please remove empty line.

**Review by seruman — CHANGES_REQUESTED** [review]

File: e2e/cp_test.go [hunk 7]
```diff
@@ -1004,6 +1004,165 @@ func TestCopyMultipleFilesToS3Bucket(t *testing.T) {
 	}
 }
 
+// adresses the #360
```
[the remark this answers is not in the document]
Comment (MuhammedCanKucukaslan) [reply e2e/cp_test.go:1007]: I thought it could help to provide context for the change, but as you said the PR itself would be sufficient. Thanks!

File: e2e/cp_test.go (hunk 3 above)
Comment (MuhammedCanKucukaslan) [reply e2e/cp_test.go]: I've removed this, and other empty lines, thanks for warning.

File: storage/url/url.go [hunk 8]
```diff
@@ -278,9 +278,37 @@ func (u *URL) Clone() *URL {
...
+		// path string won't match with the actual name of the
+		// object.
+		// e.g. base.Absolute(): "/a/*/n"
+		//      u.Absolute()   : "/a/b/n"
+		//
+		// if we don't trim substring from globCharacters on
+		// filepath.Dir() will give: "/a/*"
+		// consequently the
+		// filepath.Rel() will give: "../b/c" rather than "b/c"
+		// since "b" and "*" are not the same.
```
[the remark this answers is not in the document]
Comment (MuhammedCanKucukaslan) [reply storage/url/url.go:304]: I've added a test (TestURLSetRelative) to the _storage/url/url_test.go_ file. Thanks for suggestion.

File: storage/url/url_test.go [hunk 9]
```diff
@@ -432,3 +433,57 @@ func TestURLWithMode(t *testing.T) {
...
+		base   string
+		target string
+		expect string
+	}
+	tests := make([]testURLSetRelativeStruct, 0, 10)
+	if runtime.GOOS != "windows" {
+		tests = append(tests, []testURLSetRelativeStruct{
+			// The expectation is the path which will get us to target starting
+			// from the directory of base object.
+			{"normal file path 1", "/parent/child/object", "/parent/child2/object", "../child2/object"},
```
Comment (seruman) [inline storage/url/url_test.go:449]: I believe it would make it more readable if field names are used when defining struct literals;
```suggestion
			{
				name:   "normal file path 1",
				base:   "/parent/child/object",
				target: "/parent/child2/object",
				expect: "../child2/object",
			},

```

Comment (seruman) [reply storage/url/url_test.go:449]: As for the case names, I think they should be more descriptive; instead of `normal file path 1` something like `local_sibling_child_object` etc.  IMHO it makes it is more understandable without need to check inputs/outputs to see what it actually tests.

Case names in other tests might give some ideas.

File: storage/url/url.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (seruman) [reply storage/url/url.go:304]: Thank you 👍

**Review by seruman — APPROVED** [review]

File: CHANGELOG.md [hunk 10]
```diff
@@ -27,6 +27,7 @@
 - Updated region detection call to use current session's address resolving method ([#314](https://github.com/peak/s5cmd/issues/314))
 - Fixed a bug where lines with large tokens fail in `run` command. `sync` was failing when it finds multiple files to remove. ([#435](https://github.com/peak/s5cmd/issues/435), [#436](https://github.com/peak/s5cmd/issues/436))
 - Print usage error if given log level(`--log`) is not valid. ([#430](https://github.com/peak/s5cmd/pull/430))
+- Fixed a bug where some part of destination path is removed by `cp` and `sync` subcommands  ([#360](https://github.com/peak/s5cmd/issues/360))
```
Comment (aykutfarsak) [inline CHANGELOG.md:30]:
```suggestion
- Fixed a bug where some part of the destination path is removed by `cp` and `sync` subcommands ([#360](https://github.com/peak/s5cmd/issues/360))
```

File: e2e/cp_test.go [hunk 11]
```diff
@@ -1004,9 +1003,163 @@ func TestCopyMultipleFilesToS3Bucket(t *testing.T) {
...
+	// assert local filesystem
+	expected := fs.Expected(t, folderLayout...)
+	assert.Assert(t, fs.Equal(workdir.Path(), expected))
+	//
+	expectedS3Content := map[string]string{
+		"newfolder/child1/name.txt": "A file in parent/child1/",
+		"newfolder/child2/name.txt": "A file in parent/child2/",
+	}
+	//
+	// // assert s3
```
Comment (aykutfarsak) [inline e2e/cp_test.go:1054]:
```suggestion

	// assert s3
```

File: e2e/cp_test.go [hunk 12]
```diff
@@ -1004,9 +1003,163 @@ func TestCopyMultipleFilesToS3Bucket(t *testing.T) {
...
+	rs := result.Stdout()
+	assertLines(t, rs, map[int]compareFunc{
+		0: equals(`cp %v/parent/child1/name.txt %vchild1/name.txt`, srcpath, dstpath),
+		1: equals(`cp %v/parent/child2/name.txt %vchild2/name.txt`, srcpath, dstpath),
+	}, sortInput(true))
+
+	// assert local filesystem
+	expected := fs.Expected(t, folderLayout...)
+	assert.Assert(t, fs.Equal(workdir.Path(), expected))
+	//
```
Comment (aykutfarsak) [inline e2e/cp_test.go:1048]:
```suggestion

```

File: e2e/cp_test.go [hunk 13]
```diff
@@ -1004,9 +1003,163 @@ func TestCopyMultipleFilesToS3Bucket(t *testing.T) {
...
```
Comment (aykutfarsak) [inline e2e/cp_test.go:1102]:
```suggestion

```

File: e2e/cp_test.go [hunk 14]
```diff
@@ -1004,9 +1003,163 @@ func TestCopyMultipleFilesToS3Bucket(t *testing.T) {
...
+	expectedS3Content := map[string]string{
+		"newfolder/child1/name.txt": "A file in parent/child1/",
+		"newfolder/child2/name.txt": "A file in parent/child2/",
+	}
+	//
+	// // assert s3
```
Comment (aykutfarsak) [inline e2e/cp_test.go:1108]:
```suggestion

	// assert s3
```

File: e2e/cp_test.go [hunk 15]
```diff
@@ -1004,9 +1003,163 @@ func TestCopyMultipleFilesToS3Bucket(t *testing.T) {
...
+	result.Assert(t, icmd.Success)
+	rs := result.Stdout()
+	assertLines(t, rs, map[int]compareFunc{
+		0: equals(`cp %v/parent/child1/name.txt %vchild1/name.txt`, srcpath, dstpath),
+	}, sortInput(true))
+
+	// assert local filesystem
+	expected := fs.Expected(t, folderLayout...)
+	assert.Assert(t, fs.Equal(workdir.Path(), expected))
+	//
```
Comment (aykutfarsak) [inline e2e/cp_test.go:1150]:
```suggestion

```

File: e2e/cp_test.go [hunk 16]
```diff
@@ -1004,9 +1003,163 @@ func TestCopyMultipleFilesToS3Bucket(t *testing.T) {
...
+	expectedS3Content := map[string]string{
+		"newfolder/child1/name.txt": "A file in parent/child1/",
+	}
+	//
+	// // assert s3
```
Comment (aykutfarsak) [inline e2e/cp_test.go:1155]:
```suggestion

	// assert s3
```

File: e2e/sync_test.go [hunk 17]
```diff
@@ -246,6 +246,60 @@ func TestSyncLocalFolderToS3EmptyBucket(t *testing.T) {
...
+	rs := result.Stdout()
+	assertLines(t, rs, map[int]compareFunc{
+		0: equals(`cp %v/parent/child1/name.txt %vchild1/name.txt`, srcpath, dstpath),
+		1: equals(`cp %v/parent/child2/name.txt %vchild2/name.txt`, srcpath, dstpath),
+	}, sortInput(true))
+
+	// assert local filesystem
+	expected := fs.Expected(t, folderLayout...)
+	assert.Assert(t, fs.Equal(workdir.Path(), expected))
+	//
```
Comment (aykutfarsak) [inline e2e/sync_test.go:291]:
```suggestion

```

File: e2e/sync_test.go [hunk 18]
```diff
@@ -246,6 +246,60 @@ func TestSyncLocalFolderToS3EmptyBucket(t *testing.T) {
...
+	expectedS3Content := map[string]string{
+		"newfolder/child1/name.txt": "A file in parent/child1/",
+		"newfolder/child2/name.txt": "A file in parent/child2/",
+	}
+	//
+	// // assert s3
```
Comment (aykutfarsak) [inline e2e/sync_test.go:297]:
```suggestion

	// assert s3
```

**Review by aykutfarsak — APPROVED** [review]

File: storage/url/url_test.go [hunk 19]
```diff
@@ -432,3 +433,137 @@ func TestURLWithMode(t *testing.T) {
...
+
+func TestURLSetRelative(t *testing.T) {
+	type testcase struct {
+		name   string
+		base   string
+		target string
+		expect string
+	}
+	var tests []testcase
+	if runtime.GOOS == "windows" {
```
Comment (igungor) [inline storage/url/url_test.go:445]: Is this really necessary? We already have path separator conversion for Windows.

Comment (igungor) [reply storage/url/url_test.go:445]: If the tests cases are the same, please try to use 1 scenario for both operation systems using filepath separator.

**Review by igungor — APPROVED** [review]
