### PR TITLE
command: append object error to multierror to return non-zero exit code error

### LINKED ISSUE #304: Some errors do not result in a non-zero exit code
## System info

**OS:** Alpine Linux 3.13.1
**s5cmd version:** v1.2.1-3fc01af

## Observations

The host is resolvable and reachable, but credentials are not passed through envs:

```shell
/ $ s5cmd --log error --endpoint-url https://minio.localhost cp "s3://tmp/*" tmp/
ERROR session: fetching region failed: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
ERROR "cp s3://tmp/* tmp/": NoCredentialProviders: no valid providers in chain. Deprecated. For verbose messaging see aws.Config.CredentialsChainVerboseErrors
/ $ echo $?
0
```

The host was resolvable, unreachable:
```shell
/ $ s5cmd --log error --endpoint-url https://minio.localhost cp "s3://tmp/*" tmp/
ERROR session: fetching region failed: RequestError: send request failed
caused by: dial tcp 255.255.255.254:443: connect: connection refused
ERROR "cp s3://tmp/* tmp/": RequestError: send request failed caused by: Get "https://minio.localhost/tmp?list-type=2&prefix=": dial tcp 255.255.255.254:443: connect: connection refused
/ $ echo $?
0
```

The host is unresolvable:
```shell
/ $ s5cmd --log error --endpoint-url https://bvsdfdjsfs cp "s3://tmp/*" tmp/
ERROR session: fetching region failed: RequestError: send request failed
caused by: dial tcp: lookup bvsdfdjsfs on 127.0.0.1:53: no such host
ERROR "cp s3://tmp/* tmp/": RequestError: send request failed caused by: Get "https://bvsdfdjsfs/tmp?list-type=2&prefix=": dial tcp: lookup bvsdfdjsfs on 127.0.0.1:53: no such host
/ $ echo $?
0
```

All of that means that we can't be sure that pipelines fail in case there's something wrong with `s3cmd cp`.

### PR DESCRIPTION
**Pull request by ocakhasan**
* Creating two error objects instead of one, is to avoid data race. Since there is a goroutine running which tries to write `merror` object, there might be a data race for `merror` object in `cp`, `rm` and `select` commands. We can create 1 error object for the goroutine and 1 for the main routine, and append them at the end of the execution. 

Tested #304 's first case, it returns exit code 1. 

Resolves #304

### CODE REVIEW

File: command/cp.go [hunk 1]
```diff
@@ -290,9 +290,13 @@ func (c Copy) Run(ctx context.Context) error {
 
 	waiter := parallel.NewWaiter()
 
+	// create two different error objects instead of single object to avoid the
+	// data race for merror object, since there is a goroutine running,
+	// there might be a data rice for a single error object.
```
Comment (sonmezonur) [inline command/cp.go:295]:
```suggestion
	// there might be a data race for a single error object.
```
typo :)

File: command/rm.go [hunk 2]
```diff
@@ -97,6 +97,14 @@ func (d Delete) Run(ctx context.Context) error {
 
 	objch := expandSources(ctx, client, false, srcurls...)
 
+	// create two different error objects instead of single object to avoid the
+	// data race for merror object, since there is a goroutine running,
+	// there might be a data rice for a single error object.
```
Comment (sonmezonur) [inline command/rm.go:102]:
```suggestion
	// there might be a data race for a single error object.
```
typo :)

**Review by sonmezonur — COMMENTED** [review]
LGTM. Could you update the changelog?

File: command/select.go [hunk 3]
```diff
@@ -114,7 +114,13 @@ func (s Select) Run(ctx context.Context) error {
 		return err
 	}
 
-	var merror error
+	// create two different error objects instead of single object to avoid the
+	// data race for merror object, since there is a goroutine running,
+	// there might be a data rice for a single error object.
+	var (
+		merrorWaiter error
+		merrorObject error
```
Comment (sonmezonur) [inline command/select.go:122]:
```suggestion
		merrorObjects error
```

File: command/select.go [hunk 4]
```diff
@@ -114,7 +114,13 @@ func (s Select) Run(ctx context.Context) error {
 		return err
 	}
 
-	var merror error
+	// create two different error objects instead of single object to avoid the
+	// data race for merror object, since there is a goroutine running,
+	// there might be a data rice for a single error object.
```
Comment (sonmezonur) [inline command/select.go:119]:
```suggestion
	// there might be a data race for a single error object.
```
typo

File: command/cp.go (hunk 1 above)
Comment (ocakhasan) [reply command/cp.go]: fixed

File: command/rm.go (hunk 2 above)
Comment (ocakhasan) [reply command/rm.go]: fixed

File: command/select.go (hunk 4 above)
Comment (ocakhasan) [reply command/select.go]: fixed

File: command/select.go (hunk 3 above)
Comment (ocakhasan) [reply command/select.go]: changed to `merrorObjects`.

**Review by sonmezonur — APPROVED** [review]

**Review by aykutfarsak — APPROVED** [review]

**Review by igungor — CHANGES_REQUESTED** [review]
Could you think of a testcase to demonstrate the fix please?

File: e2e/cp_test.go [hunk 5]
```diff
@@ -3346,3 +3347,73 @@ func TestCopyRawModeAllowDestinationWithoutPrefix(t *testing.T) {
 		t.Errorf("testfile*.txt not exist in S3 bucket %v\n", dst)
 	}
 }
+
+func TestCopyFalseCredentialsExitCode1(t *testing.T) {
```
Comment (igungor) [inline e2e/cp_test.go:3351]:
```suggestion
func TestCopyExpectExitCode1OnEmptyCredentials(t *testing.T) {
```

File: e2e/cp_test.go [hunk 6]
```diff
@@ -3346,3 +3347,73 @@ func TestCopyRawModeAllowDestinationWithoutPrefix(t *testing.T) {
...
+	t.Parallel()
+
+	const bucket = "bucket"
+
+	s3client, s5cmd, cleanup := setup(t)
+	defer cleanup()
+
+	createBucket(t, s3client, bucket)
+
+	folderLayout := []fs.PathOp{
```
Comment (igungor) [inline e2e/cp_test.go:3361]: Please use a simpler test case. This might be an artifact of C/P but it is confusing to see nested files while we're only testing empty credentials scenario.

File: e2e/cp_test.go [hunk 7]
```diff
@@ -3346,3 +3347,73 @@ func TestCopyRawModeAllowDestinationWithoutPrefix(t *testing.T) {
...
+
+func TestCopyNonExistEndpointURL(t *testing.T) {
+	t.Parallel()
+
+	const bucket = "bucket"
+
+	_, s5cmd, cleanup := setup(t, withEndpointURL("nonExistEndpointURL"))
+	defer cleanup()
+
+	folderLayout := []fs.PathOp{
```
Comment (igungor) [inline e2e/cp_test.go:3395]: Please use a simpler test case. This might be an artifact of C/P but it is confusing to see nested files while we're only testing empty credentials scenario.

File: e2e/cp_test.go [hunk 8]
```diff
@@ -3346,3 +3347,73 @@ func TestCopyRawModeAllowDestinationWithoutPrefix(t *testing.T) {
...
+
+	result.Assert(t, icmd.Expected{ExitCode: 1})
+}
+
+func TestCopyNonExistEndpointURL(t *testing.T) {
+	t.Parallel()
+
+	const bucket = "bucket"
+
+	_, s5cmd, cleanup := setup(t, withEndpointURL("nonExistEndpointURL"))
```
Comment (igungor) [inline e2e/cp_test.go:3392]:
```suggestion
	_, s5cmd, cleanup := setup(t, withEndpointURL("nonExistingEndpointURL"))
```

File: e2e/util_test.go [hunk 9]
```diff
@@ -149,15 +158,19 @@ func s5cmd(workdir, endpoint string) func(args ...string) icmd.Cmd {
...
 		cmd := icmd.Command(s5cmdPath, args...)
 		env := os.Environ()
-		env = append(
-			env,
-			[]string{
-				fmt.Sprintf("AWS_ACCESS_KEY_ID=%v", defaultAccessKeyID),
-				fmt.Sprintf("AWS_SECRET_ACCESS_KEY=%v", defaultSecretAccessKey),
-			}...,
-		)
+		if os.Getenv("AWS_ACCESS_KEY_ID") == "" || os.Getenv("AWS_SECRET_ACCESS_KEY") == "" {
```
Comment (igungor) [inline e2e/util_test.go:161]: Why is this change necessary?

File: e2e/util_test.go [hunk 10]
```diff
@@ -149,15 +158,19 @@ func s5cmd(workdir, endpoint string) func(args ...string) icmd.Cmd {
...
+				[]string{
+					fmt.Sprintf("AWS_ACCESS_KEY_ID=%v", defaultAccessKeyID),
+					fmt.Sprintf("AWS_SECRET_ACCESS_KEY=%v", defaultSecretAccessKey),
+				}...,
+			)
+		}
 		cmd.Env = env
 		cmd.Dir = workdir
+
+		// fmt.Printf("environment: %v\n", os.Environ())
```
Comment (igungor) [inline e2e/util_test.go:173]: please remove dead codes.

File: e2e/cp_test.go [hunk 11]
```diff
@@ -3346,3 +3347,73 @@ func TestCopyRawModeAllowDestinationWithoutPrefix(t *testing.T) {
...
+	src = filepath.ToSlash(src)
+	dst := fmt.Sprintf("s3://%s/", bucket)
+
+	cmd := s5cmd(`AWS_ACCESS_KEY_ID=""`, `AWS_SECRET_ACCESS_KEY=""`, "cp", src, dst)
+	result := icmd.RunCmd(cmd)
+
+	result.Assert(t, icmd.Expected{ExitCode: 1})
+}
+
+func TestCopyNonExistEndpointURL(t *testing.T) {
```
Comment (igungor) [inline e2e/cp_test.go:3387]:
```suggestion
func TestCopyExpectExitCode1OnUnreachableHost(t *testing.T) {
```

File: e2e/cp_test.go (hunk 5 above)
Comment (ocakhasan) [reply e2e/cp_test.go:3351]: removed credentials test because, it is not related with our case. Same test case works same with `master` branch.

File: e2e/cp_test.go (hunk 6 above)
Comment (ocakhasan) [reply e2e/cp_test.go:3361]: deleted the complex file structures.

File: e2e/cp_test.go (hunk 7 above)
Comment (ocakhasan) [reply e2e/cp_test.go:3395]: deleted the complex file structures.

File: e2e/cp_test.go (hunk 8 above)
Comment (ocakhasan) [reply e2e/cp_test.go:3392]: changed to `nonExistingEndpointURL`.

File: e2e/util_test.go (hunk 9 above)
Comment (ocakhasan) [reply e2e/util_test.go:161]: I wanted to test the credentials case, to do that, I thought , it should use credentials setted by myself. Therefore, I added an if condition to check if any of the credentials are given. But the same test case worked same with `master` branch, therefore I deleted it.

File: e2e/util_test.go (hunk 10 above)
Comment (ocakhasan) [reply e2e/util_test.go:173]: deleted the unnecessary comment.

File: e2e/cp_test.go (hunk 11 above)
Comment (ocakhasan) [reply e2e/cp_test.go:3387]: changed to `TestCopyExpectExitCode1OnUnreachableHost`.

**Comment by ocakhasan** [comment]
@igungor can you please review it again?

**Review by igungor — APPROVED** [review]
