### PR TITLE
command/cp: fix mime type inference

### LINKED ISSUE #214: cp command incorrectly infers MIME type
When using s5cmd and the `cp` command on a set of statically-generated web files to upload to an S3 bucket, the MIME types are not being correctly inferred. This causes some of them (ex. CSS files) to be fetched with the wrong response headers being returned. When using awscli and the `sync` command, for example, this is not an issue and the files are uploaded correctly.

Produces error:
`s5cmd cp -s -n -u <local_dir> s3://bucket_name`

Success:
`aws s3 sync --size-only --delete <local_dir> s3://bucket_name`

### PR DESCRIPTION
**Pull request by fbarotov**
Resolves #214

### CODE REVIEW

File: command/cp_test.go [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+					<html>
+						<head>
+							<title>Hello World</title>
+						</head>
+						<body>
+							<p>Hello, World! I am s5cmd :)</p>
+						</body>
+					</html>
+					`,
+			expectedContentType: "text/plain; charset=utf-8",
```
Comment (igungor) [inline command/cp_test.go:41]: I'm surprised to see `text/plain` here instead of `text/html`. Please take a look at https://github.com/peak/s5cmd/blob/master/e2e/cp_test.go#L657.

**Review by ilkinulas — APPROVED** [review]

File: command/cp_test.go (hunk 1 above)
Comment (fbarotov) [reply command/cp_test.go]: thanks, yes it should be `text/html` rather than `text/plain`.

**Review by igungor — APPROVED** [review]
