### PR TITLE
Remove stat flag unnecessary prints

### LINKED ISSUE #452: --stat flag unnecessarily prints with help & version subcommands
I'm currently using the v2.0.0-beta.2-c978e4a
l
Using --stat flag with `version` and `help` subcommands prints

>Operation	Total	Error	Success	

at the end of output. Although it does not affect functionality, it is not expected to work with this subcommands. It should only work when there are some operations (e.g. cp, rm) executed.

To reproduce simply write
` s5cmd --stat version`

### PR DESCRIPTION
**Pull request by boraberke**
Fixes #452

### CODE REVIEW

File: log/log.go [hunk 1]
```diff
@@ -37,6 +37,12 @@ func Info(msg Message) {
 	global.printf(levelInfo, msg, os.Stdout)
 }
 
+// Stat prints stat message regardless of the log level with info print formatting.
+// It uses printfHelper instead of printf to ignore the log level condition.
+func Stat(msg Message) {
+	global.printfHelper(levelInfo, msg, os.Stdout)
+}
+
```
[the remark this answers is not in the document]
Comment (boraberke) [reply log/log.go:45]: I will now close this and wait for #451 to be merged. Then I can open another pull request for changes from [this commit](https://github.com/peak/s5cmd/pull/455/commits/809dc9fb6a2739a165fe32eb40145d61838dc8aa) which fixes #452. Thank you for pointing it out.

File: log/log_test.go [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+		"info",
+		"error",
+	}
+	for _, l := range levels {
+		testStatHelper(l, t)
+	}
+	// testStatHelper method closes and remakes the outputCh
+	// but this creates a useless channel at the end too
+	// so we need to close it at the end.
+	Close()
```
[the remark this answers is not in the document]
Comment (boraberke) [reply log/log_test.go:26]: We addressed this issue in [this commit](https://github.com/peak/s5cmd/pull/451/commits/6fbf7530a3c968c6d81a06a768d7acb146c334b3) which is waiting #451 to be merged. Thanks!

File: log/log.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (seruman) [reply log/log.go:45]: You may keep the PR open then rebase once https://github.com/peak/s5cmd/pull/451 merges.

[the remark this answers is not in the document]
Comment (boraberke) [reply log/log.go:45]: Okay, will be waiting until #451 to be merged then.

[the remark this answers is not in the document]
Comment (boraberke) [reply log/log.go]: I rebased this PR as #451 has been merged.

File: e2e/app_test.go [hunk 3]
```diff
@@ -69,7 +69,53 @@ func TestAppRetryCount(t *testing.T) {
 	}
 }
 
-// Checks if the stats are written at the end of each log level output.
+// Checks if --stat flag does not print when used with help & version commands
+func TestAppDashStatUnnecessaryPrints(t *testing.T) {
```
Comment (igungor) [inline e2e/app_test.go:73]: This test looks the same as `TestAppDashStat`. We should merge them.

Comment (boraberke) [reply e2e/app_test.go]: Just merged `TestAppDashStatUnnecessaryPrints` and  `TestAppDashStat` into one under the name `TestAppDashStat`.

File: e2e/app_test.go [hunk 4]
```diff
@@ -69,36 +69,55 @@ func TestAppRetryCount(t *testing.T) {
...
 	const (
-		bucket      = "bucket"
-		fileContent = "this is a file content"
-		dst         = "."
-		src         = "file1.txt"
+		bucket                  = "bucket"
+		fileContent             = "this is a file content"
+		dst                     = "."
+		src                     = "file1.txt"
+		ExpectedOutputIfPrinted = "Operation\tTotal\tError\tSuccess\t"
```
Comment (igungor) [inline e2e/app_test.go:83]: Can we make it private?

File: e2e/app_test.go [hunk 5]
```diff
@@ -69,36 +69,55 @@ func TestAppRetryCount(t *testing.T) {
...
 	)
 
 	testcases := []struct {
```
Comment (igungor) [inline e2e/app_test.go:86]: Let's change the table test setup. I think it's easier to read the test with 2 fields:

`command` and `expectedOutput`.

```go
testcases := []struct{
	command string
	expectedOutput string
}{
	{
		command: "--stat --log trace cp . s3://bucket/object",
		expectedOutput: expectedOutputIfPrinted,
	},
}
```

Test logic could be:

```go
cmd = s5cmd(strings.Fields(tc.command)...)
result := icmd.RunCmd(cmd)
result.Assert(t, icmd.Success)

out := result.Stdout()
assert.Assert(t, strings.Contains(out, tc.expectedOutput))
```

**Review by igungor — APPROVED** [review]

File: command/app.go [hunk 6]
```diff
@@ -143,7 +143,11 @@ var app = &cli.App{
 	},
 	After: func(c *cli.Context) error {
 		if c.Bool("stat") {
```
Comment (sonmezonur) [inline command/app.go:145]: nit: this might be a single line. also no need to add issue reference in comment

```suggestion
		if c.Bool("stat") && len(stat.Statistics()) > 0 {
```

Comment (boraberke) [reply command/app.go]: Fixed 👍

**Review by sonmezonur — APPROVED** [review]

**Review by seruman — APPROVED** [review]

**Comment by sonmezonur** [comment]
@boraberke could you rebase your branch?
