### PR TITLE
storage/s3: Fix proxy with no-verify-ssl flag

### LINKED ISSUE #445: s5cmd Doesn't respect proxy environment variables
The AWS CLI + Boto3 support setting environment variables to pass requests through a proxy. In my case, we require this functionality because we use a proxy to route requests from our dev network to our VPC.

The environment variables that are set are:
`https_proxy`
`http_proxy`
`HTTPS_PROXY`
`HTTP_PROXY`

Using the AWS CLI, the following command succeeds:
```
aws --region us-east-2 --no-verify-ssl s3 ls s3://path/to/prefix
```

However, using `s5cmd` (v1.4.0), the analagous command fails:
```
s5cmd --log debug --no-verify-ssl ls s3://path/to/prefix
```

with the following output
```
DEBUG retryable error: RequestError: send request failed
caused by: dial tcp 52.219.80.130:443: connect: connection refused
DEBUG retryable error: RequestError: send request failed
caused by: dial tcp 52.219.80.130:443: connect: connection refused
DEBUG retryable error: RequestError: send request failed
caused by: dial tcp 52.219.80.130:443: connect: connection refused
DEBUG retryable error: RequestError: send request failed
caused by: dial tcp 52.219.80.130:443: connect: connection refused
DEBUG retryable error: RequestError: send request failed
caused by: dial tcp 52.219.80.130:443: connect: connection refused
DEBUG retryable error: RequestError: send request failed
caused by: dial tcp 52.219.80.130:443: connect: connection refused
DEBUG retryable error: RequestError: send request failed
caused by: dial tcp 52.219.80.130:443: connect: connection refused
DEBUG retryable error: RequestError: send request failed
caused by: dial tcp 52.219.142.89:443: connect: connection refused
DEBUG retryable error: RequestError: send request failed
caused by: dial tcp 52.219.106.241:443: connect: connection refused
DEBUG retryable error: RequestError: send request failed
caused by: dial tcp 52.219.99.57:443: connect: connection refused
DEBUG retryable error: RequestError: send request failed
caused by: dial tcp 52.219.88.226:443: connect: connection refused
ERROR session: fetching region failed: RequestError: send request failed
caused by: dial tcp 52.219.88.226:443: connect: connection refused
DEBUG retryable error: RequestError: send request failed
caused by: Get "https://path.s3.us-east-2.amazonaws.com/?delimiter=%2F&list-type=2&prefix=to%2Fprefix": dial tcp 52.219.84.232:443: connect: connection refused
DEBUG retryable error: RequestError: send request failed
caused by: Get "https://path.s3.us-east-2.amazonaws.com/?delimiter=%2F&list-type=2&prefix=to%2Fprefix": dial tcp 52.219.84.232:443: connect: connection refused
DEBUG retryable error: RequestError: send request failed
caused by: Get "https://path.s3.us-east-2.amazonaws.com/?delimiter=%2F&list-type=2&prefix=to%2Fprefix": dial tcp 52.219.84.232:443: connect: connection refused
DEBUG retryable error: RequestError: send request failed
caused by: Get "https://path.s3.us-east-2.amazonaws.com/?delimiter=%2F&list-type=2&prefix=to%2Fprefix": dial tcp 52.219.84.232:443: connect: connection refused
DEBUG retryable error: RequestError: send request failed
caused by: Get "https://path.s3.us-east-2.amazonaws.com/?delimiter=%2F&list-type=2&prefix=to%2Fprefix": dial tcp 52.219.84.232:443: connect: connection refused
DEBUG retryable error: RequestError: send request failed
caused by: Get "https://path.s3.us-east-2.amazonaws.com/?delimiter=%2F&list-type=2&prefix=to%2Fprefix": dial tcp 52.219.84.232:443: connect: connection refused
DEBUG retryable error: RequestError: send request failed
caused by: Get "https://path.s3.us-east-2.amazonaws.com/?delimiter=%2F&list-type=2&prefix=to%2Fprefix": dial tcp 52.219.84.232:443: connect: connection refused
DEBUG retryable error: RequestError: send request failed
caused by: Get "https://path.s3.us-east-2.amazonaws.com/?delimiter=%2F&list-type=2&prefix=to%2Fprefix": dial tcp 52.219.99.34:443: connect: connection refused
DEBUG retryable error: RequestError: send request failed
caused by: Get "https://path.s3.us-east-2.amazonaws.com/?delimiter=%2F&list-type=2&prefix=to%2Fprefix": dial tcp 52.219.105.122:443: connect: connection refused
DEBUG retryable error: RequestError: send request failed
caused by: Get "https://path.s3.us-east-2.amazonaws.com/?delimiter=%2F&list-type=2&prefix=to%2Fprefix": dial tcp 52.219.110.170:443: connect: connection refused
DEBUG retryable error: RequestError: send request failed
caused by: Get "https://path.s3.us-east-2.amazonaws.com/?delimiter=%2F&list-type=2&prefix=to%2Fprefix": dial tcp 52.219.109.122:443: connect: connection refused
ERROR "ls s3://path/to/prefix": RequestError: send request failed caused by: Get "https://path.s3.us-east-2.amazonaws.com/?delimiter=%2F&list-type=2&prefix=to%2Fprefix": dial tcp 52.219.109.122:443: connect: connection refused

```

Is there some way to get s5cmd to use the proxy variables? Or is this unsupported?

### PR DESCRIPTION
**Pull request by boraberke**
This change fixes the problem where proxy is ignored when no-verify-ssl flag is used.

- Test environment is created to test proxy support: proxy_fake.go is added.

Fixes #445

### CODE REVIEW

File: e2e/s3_fake.go [hunk 1]
```diff
@@ -58,5 +58,11 @@ func s3ServerEndpoint(t *testing.T, testdir *fs.Dir, loglvl, backend string, tim
 		// after each test.
 	}
 
+	if enableProxy {
+		splitURL := strings.Split(s3srv.URL, ":")
```
[the remark this answers is not in the document]
Comment (boraberke) [reply e2e/s3_fake.go]: [SplitHostPort](https://pkg.go.dev/net#SplitHostPort) is not suitable for parsing standard URLs as it only accepts urls without scheme. However we can use [ParseRequestURI](https://pkg.go.dev/net/url#ParseRequestURI) to grab port as follows:
```
parsedUrl, err := url.ParseRequestURI(s3srv.URL)
if err != nil {
	t.Fatal(err)
}
proxyEnabledURL := "http://localhost.:" + parsedUrl.Port()
```

I will change to[ParseRequestURI](https://pkg.go.dev/net/url#ParseRequestURI) if it is better than `strings.Split`.

[the remark this answers is not in the document]
Comment (igungor) [reply e2e/s3_fake.go]: Hmm, okay. We can use `url.Parse`. It's much better than string split.

**Review by ilkinulas — APPROVED** [review]

File: e2e/proxy_fake.go [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+	if prior, ok := header["X-Forwarded-For"]; ok {
+		host = strings.Join(prior, ", ") + ", " + host
+	}
+	header.Set("X-Forwarded-For", host)
+}
+
+type proxy struct {
+}
+
+var requests = make(map[string]bool)
```
Comment (igungor) [inline e2e/proxy_fake.go:52]: I don't like the idea keeping a global variable to count requests. A better approach would be to store request counts in the `proxy` type and atomically increment success/error counters.

File: e2e/proxy_fake.go [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+
+func (p *proxy) ServeHTTP(wr http.ResponseWriter, req *http.Request) {
+	//log.Println(req.RemoteAddr, " ", req.Method, " ", req.URL)
```
Comment (igungor) [inline e2e/proxy_fake.go:55]: Please remove any dead codes or unnecessary comments.

File: e2e/proxy_fake.go [hunk 4]
```diff
@@ -0,0 +1,117 @@
...
+	if req.URL.Scheme != "http" && req.URL.Scheme != "https" {
+		msg := "unsupported protocol scheme " + req.URL.Scheme
+		http.Error(wr, msg, http.StatusBadRequest)
+		log.Println(msg)
+		return
+	}
+	//We need to explicitly set New Transport with no Proxy to make
```
Comment (igungor) [inline e2e/proxy_fake.go:62]: whitespace after `//`

File: e2e/proxy_fake.go [hunk 5]
```diff
@@ -0,0 +1,117 @@
...
+	if err != nil {
+		http.Error(wr, "Server Error", http.StatusInternalServerError)
+		log.Fatal("ServeHTTP:", err)
+	}
+	if resp.StatusCode == http.StatusOK {
+		requests[req.RemoteAddr] = true
+	} else {
+		requests[req.RemoteAddr] = false
+	}
+	defer resp.Body.Close()
```
Comment (igungor) [inline e2e/proxy_fake.go:88]: Let's call defer after error check.

File: e2e/app_test.go [hunk 6]
```diff
@@ -129,6 +130,42 @@ func TestAppDashStat(t *testing.T) {
...
+		{
+			name: "with no-verify-ssl flag",
+			flag: "--no-verify-ssl",
+		},
+	}
+	for _, tc := range testcases {
+		tc := tc
+		t.Run(tc.name, func(t *testing.T) {
+			httpProxy, cleanupProxy := proxyFake()
+			defer cleanupProxy()
```
Comment (igungor) [inline e2e/app_test.go:152]: Please add newlines when necessary for readability. This function code is not easy on the eye :)

File: e2e/proxy_fake.go [hunk 7]
```diff
@@ -0,0 +1,105 @@
...
+	// If we aren't the first proxy retain prior
+	// X-Forwarded-For information as a comma+space
+	// separated list and fold multiple headers into one.
+	if prior, ok := header["X-Forwarded-For"]; ok {
+		host = strings.Join(prior, ", ") + ", " + host
+	}
+	header.Set("X-Forwarded-For", host)
+}
+
+type proxy struct {
```
Comment (igungor) [inline e2e/proxy_fake.go:50]: Let's call it `httpProxy`.

File: e2e/proxy_fake.go [hunk 8]
```diff
@@ -0,0 +1,105 @@
...
+	successReqs int64
+	errorReqs   int64
+}
+
+func (p *proxy) ServeHTTP(wr http.ResponseWriter, req *http.Request) {
+
```
Comment (igungor) [inline e2e/proxy_fake.go:56]: Please remove empty line after the signatures.

File: e2e/proxy_fake.go [hunk 9]
```diff
@@ -0,0 +1,105 @@
...
+	if req.URL.Scheme != "http" && req.URL.Scheme != "https" {
+		msg := "unsupported protocol scheme " + req.URL.Scheme
+		http.Error(wr, msg, http.StatusBadRequest)
+		log.Println(msg)
```
Comment (igungor) [inline e2e/proxy_fake.go:60]: We can remove logging. `http.Error` will write the error to response.

File: e2e/proxy_fake.go [hunk 10]
```diff
@@ -0,0 +1,105 @@
...
+	client := &http.Client{
+		Transport: &http.Transport{Proxy: nil},
+	}
+	// http: Request.RequestURI can't be set in client requests.
+	// http://golang.org/src/pkg/net/http/client.go
+	req.RequestURI = ""
+
+	delHopHeaders(req.Header)
+
+	if clientIP, _, err := net.SplitHostPort(req.RemoteAddr); err == nil {
```
Comment (igungor) [inline e2e/proxy_fake.go:75]: I don't think we need `x-forwarded-for` header for this test. Let's remove it for simplicity.

File: e2e/proxy_fake.go [hunk 11]
```diff
@@ -0,0 +1,105 @@
...
+		appendHostToXForwardHeader(req.Header, clientIP)
+	}
+
+	resp, err := client.Do(req)
+	if err != nil {
+		http.Error(wr, "Server Error", http.StatusInternalServerError)
+		log.Fatal("ServeHTTP:", err)
```
Comment (igungor) [inline e2e/proxy_fake.go:82]: Remove log line.

File: e2e/proxy_fake.go [hunk 12]
```diff
@@ -0,0 +1,105 @@
...
+	}
+	delHopHeaders(resp.Header)
+
+	copyHeader(wr.Header(), resp.Header)
+	wr.WriteHeader(resp.StatusCode)
+	io.Copy(wr, resp.Body)
+}
+
+func (p *proxy) isSuccessful(totalReqs int64) bool {
+	return totalReqs == p.successReqs && p.errorReqs == 0
```
Comment (igungor) [inline e2e/proxy_fake.go:99]: `successReqs` and `errorReqs` are atomically incremented. You should not access them directly, instead use `atomic.LoadInt64`.

File: e2e/proxy_fake.go [hunk 13]
```diff
@@ -0,0 +1,105 @@
...
+}
+
+func proxyFake(p *proxy) (string, func()) {
```
Comment (igungor) [inline e2e/proxy_fake.go:102]: Proxy is not fake, it's not fully featured but very real :)

We can rename this function as `setupProxy`. Since we're at it, let's rename this filename to `proxy.go`.

File: e2e/proxy_fake.go [hunk 14]
```diff
@@ -0,0 +1,105 @@
...
+	}
+}
+
+func delHopHeaders(header http.Header) {
+	for _, h := range hopHeaders {
+		header.Del(h)
+	}
+}
+
+func appendHostToXForwardHeader(header http.Header, host string) {
```
Comment (igungor) [inline e2e/proxy_fake.go:40]: We should not need this function to test proxy.

File: e2e/app_test.go [hunk 15]
```diff
@@ -132,6 +133,50 @@ func TestAppDashStat(t *testing.T) {
...
+			name: "with no-verify-ssl flag",
+			flag: "--no-verify-ssl",
+		},
+	}
+	for _, tc := range testcases {
+		tc := tc
+		t.Run(tc.name, func(t *testing.T) {
+			var totalReqs int64 = 1
+
+			pxy := proxy{successReqs: 0, errorReqs: 0}
```
Comment (igungor) [inline e2e/app_test.go:156]: After changing `proxy` to `httpProxy`, could you rename the variable name to `proxy` please?

Also there's no need to initialize `successReqs` and `errorReqs` here since zero value of these fields are already `0`.

File: e2e/app_test.go [hunk 16]
```diff
@@ -132,6 +133,50 @@ func TestAppDashStat(t *testing.T) {
...
+		},
+		{
+			name: "with no-verify-ssl flag",
+			flag: "--no-verify-ssl",
+		},
+	}
+	for _, tc := range testcases {
+		tc := tc
+		t.Run(tc.name, func(t *testing.T) {
+			var totalReqs int64 = 1
```
Comment (igungor) [inline e2e/app_test.go:154]: `const expectedReqs = 1`

**Review by igungor — APPROVED** [review]
Looks good!
